"""
File from module `pyvelov`. Contains all functions required to communicate with API.py

Datas API:
----------
Grand Lyon Metropole (https://data.grandlyon.com/jeux-de-donnees/stations-velo-v-metropole-lyon-disponibilites-temps-reel/api)


File JSON generated by API :
https://download.data.grandlyon.com/ws/rdata/jcd_jcdecaux.jcdvelov/all.json?maxfeatures=-1&start=1
"""

from urllib.request import urlretrieve
import json
import os

URL_API = 'https://download.data.grandlyon.com/ws/rdata/jcd_jcdecaux.jcdvelov/all.json?maxfeatures=-1&start=1'

class APIConnection:
    """
    Class represents a connection with API and retrieve datas from JSON file.

    Attributes
    -----------
    - `datas`(tuple):Tuple of dictionnaries
    """

    def __init__(self):
        """Constructor.
        Connection with API, retrieve JSON file and parse it.

        Returns
        -------
            `None`
        """
        self.datas = None
        self.nbStations = 0

        #Connection with API
        try:
            request = urlretrieve(URL_API)
        except:
            return None
        

        temp_file_path = request[0]
        #Open file downloaded read and close
        try:
            json_file = open(temp_file_path,'r')
            json_datas = json_file.read()
            json_file.close()
        except:
            return None

        #Delete temp file
        try:
            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)
        except:
            pass
        
        #JSON load
        try:
            datas = json.loads(json_datas)
        except:
            return None
        
        self.datas = tuple(datas['values'])
        self.nbStations = len(self.datas)
        return None

    def getDatas(self):
        return self.datas


def createAPIInstance():
    connection = APIConnection()

pass