"""
File from module `pyvelov`. Contains all functions required to communicate with API.py

Datas API:
----------
Grand Lyon Metropole (https://data.grandlyon.com/jeux-de-donnees/stations-velo-v-metropole-lyon-disponibilites-temps-reel/api)


File JSON generated by API :
https://download.data.grandlyon.com/ws/rdata/jcd_jcdecaux.jcdvelov/all.json?maxfeatures=-1&start=1
"""

from urllib.request import urlretrieve
import json

class APIConnection:
    """
    Class represents a connection with API and retrieve datas from JSON file.
    """

    URL_API = 'https://download.data.grandlyon.com/ws/rdata/jcd_jcdecaux.jcdvelov/all.json?maxfeatures=-1&start=1'

    def __init__(self):
        try:
            #Connection with API
            request = urlretrieve(self.URL_API)
            json_file = request[0]
            
            datas = json.loads(json_file)

            print(datas)
        except:
            pass

pass